import { Button, VerticalBox, HorizontalBox, GroupBox} from "std-widgets.slint";
import { CellList } from "cell_list.slint";
import { Log } from "log.slint";
import { Serial } from "serial.slint"; 

export global SerialService {
    in-out property <[string]> serials;
    callback refresh-clicked;
    callback connect-clicked(string);
}

export component AppWindow inherits Window {
    width: 800px;
    height: 600px;

    title: "CawBMS - Desktop";
    background: #000e;

    init => {
        debug("AppWindow init");
    }

    VerticalBox {
        HorizontalBox { 
            CellList {}
            Serial {
                height: 100px;
                width: 280px;
                cbx-model: SerialService.serials;
                refresh-clicked => {
                    SerialService.refresh-clicked();
                }

                connect-clicked(current-value) => {
                    SerialService.connect-clicked(current-value);
                }

            }
        }
        Log {}
    }
}