import { Button, VerticalBox, HorizontalBox, GroupBox} from "std-widgets.slint";
import { CellList } from "cell_list.slint";
import { Log } from "log.slint";
import { Home } from "home.slint";

export global AppService {
    in-out property <bool> device-state : false;
}

export component AppWindow inherits Window {
    width: 800px;
    height: 600px;
    title: "CawBMS - Desktop";
    background: #000e;
    init => {
        debug("AppWindow init");
    }
    if AppService.device-state:
        VerticalBox {
            HorizontalBox { 
                CellList {}
            }
            Log {}
        }
    if !AppService.device-state:
        Home {  }
    
    
}