import { HorizontalBox, VerticalBox, ProgressIndicator } from "std-widgets.slint";

export component CellInfo inherits Rectangle {
    in-out property name <=> cell_nbr.text;
    in-out property progress <=> p.progress;

    property <int> p_val: p.progress * 100;
    HorizontalBox {
        cell_nbr := Text {
            color: #fff;
        }
        p := ProgressIndicator {
            progress: 0.5;
        }
        Text {
            text: p_val + "%";
            color: #fff;
        }
    }
    
}