import { HorizontalBox, VerticalBox } from "std-widgets.slint";

export component Home inherits Rectangle {
    background: #00000085;
    VerticalBox {
        alignment: center;
        HorizontalBox {
            alignment: center;
            Rectangle{
                border-radius: 10px;
                width: 300px;
                height: 200px;
                background: #ffffff1e;
                VerticalBox {
                    alignment: center;
                    spacing: 20px;
                    Text {
                        horizontal-alignment: center;
                        font-size: 30px;
                        font-weight: 700;
                        color: #00f964;
                        text: @tr("CawBMS");
                    }

                    Text {
                        horizontal-alignment: center;
                        font-size: 20px;
                        font-weight: 700;
                        color: #ccc;
                        text: @tr("Search device ...");
                    }
                    HorizontalBox {
                        alignment: center;
                        Rectangle {
                            border-radius: 5px;
                            background: #fff;
                            height: 30px;
                            width: parent.width / 2 * abs(sin(360deg * animation-tick() / 3s));
                        }
                    }
                    
                }
                
            }
        }
    }
} 