import { HorizontalBox, VerticalBox} from "std-widgets.slint";

export component IconButton inherits Rectangle {
    in-out property <image> icon;
    callback clicked <=> touch.clicked;

    img := Image {
        source: root.icon;
        colorize: touch.pressed ? #fff : #fffc;
        width: parent.width;
        height: parent.height;
    }
    
    touch := TouchArea {
    }
} 

export component ToolButton inherits Rectangle {
    callback clicked;
    in property <string> text <=> txt.text;
    in-out property <bool> enable;
    background: enable ? touch.pressed ? #fff : #fffc : #666;
    border-radius: 5px;
    txt := Text {
        width: parent.width;
        height: parent.height;
        color: #333;
        vertical-alignment: center;
        horizontal-alignment: center;
    }
    
    touch := TouchArea {
        clicked => {
            if (root.enable) {
                root.clicked();
            }
        }
    }
} 